version: "3"
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    restart: always
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 6s
      timeout: 60s
      retries: 10
  api:
    image: golang:1.21
    working_dir: /go/src/github.com/ryokosuge/api
    command: ["make", "dev"]
    volumes:
      - ./api:/go/src/github.com/ryokosuge/api
      - ./resources/credential.json:/app/credential.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential.json
      - PORT=8080
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE_NAME=test
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/ok || exit 1"]
      interval: 6s
      timeout: 60s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
  web:
    image: node:21.3-alpine
    working_dir: /app
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
      - ./web/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./resources/credential.json:/app/credential.json
    entrypoint: ["/docker-entrypoint.sh"]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential.json
      - API_URL=http://api:8080/query
    ports:
      - 3000:3000
    depends_on:
      api:
        condition: service_healthy

volumes:
  web_node_modules:
