version: "3"
services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    restart: always
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-proot"]
      interval: 6s
      timeout: 60s
      retries: 10
  api:
    image: golang:1.23
    working_dir: /go/src/github.com/ryokosuge/api
    command: ["make", "dev"]
    volumes:
      - ./api:/go/src/github.com/ryokosuge/api
      - ./resources/credential.json:/app/credential.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential.json
      - PORT=8080
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE_NAME=test
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8080/ok || exit 1"]
      interval: 6s
      timeout: 60s
      retries: 10
    depends_on:
      db:
        condition: service_healthy
  web:
    image: node:20.18-alpine
    working_dir: /app/web
    volumes:
      - ./web:/app/web
      - web_node_modules:/app/web/node_modules
      - ./web/docker-entrypoint.sh:/app/web/docker-entrypoint.sh:ro
      - ./resources/credential.json:/app/credential.json
    entrypoint: ["/app/web/docker-entrypoint.sh"]
    environment:
      - NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyCOjjqB8DorXrfikru0sPfqw8p4CcN6dQk
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=nextjs-golang-graphql-monorepo.firebaseapp.com
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=nextjs-golang-graphql-monorepo
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=nextjs-golang-graphql-monorepo.appspot.com
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=452395134855
      - NEXT_PUBLIC_FIREBASE_APP_ID=1:452395134855:web:68d3be8253bdf954e4ad22
      - NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=G-HXKD6W0KT7
      - GOOGLE_CLOUD_PROJECT=nextjs-golang-graphql-monorepo
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential.json
      - API_URL=http://api:8080/query
    ports:
      - 3000:3000
    depends_on:
      api:
        condition: service_healthy

volumes:
  web_node_modules:
