version: "3"
services:
  api:
    image: golang:1.20
    working_dir: /go/src/github.com/ryokosuge/api
    command: ["make", "dev"]
    volumes:
      - ./api:/go/src/github.com/ryokosuge/api
      - ./resources/credential.json:/app/credential.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential.json
    ports:
      - 8080:8080
  web:
    image: node:18.16-alpine
    working_dir: /app
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
      - ./web/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./resources/credential.json:/app/credential.json
    entrypoint: ["/docker-entrypoint.sh"]
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credential.json
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  web_node_modules:
