version: "2.4"
services:
  web:
    image: node:18.16-alpine
    working_dir: /app
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
      - ./web/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    entrypoint: ["/docker-entrypoint.sh"]
    ports:
      - 3000:3000

volumes:
  web_node_modules:
