import { ChakraUIProviders } from "@/containers/chakra-ui";
import { AuthProvider } from "@/context/auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

const Layout = ({ children }: Props) => {
  return (
    <html lang="en">
      <body>
        <ChakraUIProviders>
          <AuthProvider>{children} </AuthProvider>
        </ChakraUIProviders>
      </body>
    </html>
  );
};

export default Layout;
