name: PR Web

on:
  pull_request:
    paths:
      - "web/**"

defaults:
  run:
    working-directory: web

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd && ls -la
      - uses: actions/setup-node@v3
        with:
          node-version-file: "../.node-version"
          cache: "yarn"
      - run: yarn
      - run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pwd && ls -la
      - uses: actions/setup-node@v3
        with:
          node-version-file: "../.node-version"
          cache: "yarn"
      - run: yarn
      - run: yarn build
