name: PR Web

on:
  pull_request:
    paths:
      - "web/**"

env:
  NODE_VERSION: 18.16

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "../.node-version"
          cache: "yarn"
      - run: yarn
      - run: yarn lint

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "../.node-version"
          cache: "yarn"
      - run: yarn
      - run: yarn build
